# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

of_dyn <- function(theta, nu_hat, x, tau, Omega, WN, QN, AR1) {
    .Call('_nsgmwm_of_dyn', PACKAGE = 'nsgmwm', theta, nu_hat, x, tau, Omega, WN, QN, AR1)
}

grad_of_dyn <- function(theta, nu_hat, x, tau, Omega, WN, QN, AR1) {
    .Call('_nsgmwm_grad_of_dyn', PACKAGE = 'nsgmwm', theta, nu_hat, x, tau, Omega, WN, QN, AR1)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_nsgmwm_RcppExport_registerCCallable', PACKAGE = 'nsgmwm')
})
