# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Objective function for estimating dynamic GMWM parameters
#' 
#' @param theta  A vector of parameter
#' @param nu_hat A matrix of wavelet variances
#' @param x      A vector of data
#' @param tau    A vector containing the scales
#' @param Omega  A matrix of weights
#' @param WN     A boolean inidicating whether a gaussian White Noise is 
#' included in the model
#' @param QN     A boolean inidicating whether a Quantization Noise is included 
#' in the model
#' @param AR1    A non-negative integer indicating the number of Autoregressive 
#' process(es) of order 1 to be included in the model
#' @return Returns a double $$ \frac{1}{2}\frac{1}{K}\sum_{k=1}^K\lVert\hat{\nu}_k - \nu(\theta,x_k)\rVert^2_{\Omega} $$
#' @export
of_dyn <- function(theta, nu_hat, x, tau, Omega, WN, QN, AR1) {
    .Call('_nsgmwm_of_dyn', PACKAGE = 'nsgmwm', theta, nu_hat, x, tau, Omega, WN, QN, AR1)
}

#' Gradient of the objective function for estimating dynamic GMWM parameters
#' 
#' @param theta  A vector of parameter
#' @param nu_hat A matrix of wavelet variances
#' @param x      A vector of data
#' @param tau    A vector containing the scales
#' @param Omega  A matrix of weights
#' @param WN     A boolean inidicating whether a gaussian White Noise is 
#' included in the model
#' @param QN     A boolean inidicating whether a Quantization Noise is included 
#' in the model
#' @param AR1    A non-negative integer indicating the number of Autoregressive 
#' process(es) of order 1 to be included in the model
#' @return Returns a vector $$ \frac{1}{K}\sum_{k=1}^K(\hat{\nu}_k - \nu(\theta,x_k))\Omega\frac{\partial}{\partial\theta}\nu(\theta,x_k) $$
#' @export
grad_of_dyn <- function(theta, nu_hat, x, tau, Omega, WN, QN, AR1) {
    .Call('_nsgmwm_grad_of_dyn', PACKAGE = 'nsgmwm', theta, nu_hat, x, tau, Omega, WN, QN, AR1)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_nsgmwm_RcppExport_registerCCallable', PACKAGE = 'nsgmwm')
})
